import csv
import os

# --- Configuration ---
CSV_FILE_PATH = r'd:\healthOffice\all_moh_facilities.csv'
OUTPUT_SQL_PATH = r'd:\healthOffice\backend\db\seed_facilities.sql'

# --- Mappings ---
# Map Arabic 'النوع' to English codes for 'facility_type'
FACILITY_TYPE_MAP = {
    'مستشفى عام': 'HOSPITAL',
    'مستشفى تخصصي': 'SPECIALIZED_HOSPITAL',
    'مركز': 'CENTER',
    'عيادة': 'CLINIC',
    'مختبر': 'LAB',
    'اشعة': 'IMAGING_CENTER',
    'معمل': 'DENTAL_LAB',
    'صيدلية': 'PHARMACY'
}

# --- Script ---
def escape_sql(val):
    if val is None:
        return 'NULL'
    # Escape single quotes for SQL
    return "'" + str(val).replace("'", "''") + "'"

def generate_sql():
    print(f"Reading from: {CSV_FILE_PATH}")
    
    if not os.path.exists(CSV_FILE_PATH):
        print(f"Error: File not found at {CSV_FILE_PATH}")
        return

    sql_statements = []
    sql_statements.append("-- Seed data for facilities from CSV")
    sql_statements.append("-- Generated by generate_seed_facilities.py\n")
    
    # Use utf-8-sig to handle BOM if present, or just utf-8
    try:
        with open(CSV_FILE_PATH, mode='r', encoding='utf-8-sig') as csvfile:
            reader = csv.DictReader(csvfile)
            
            count = 0
            for row in reader:
                count += 1
                
                # Extract CSV columns
                # Headers: اسم المرفق,النوع,نوع المنشأة,القطاع,الحالة التشغيلية,المحافظة,المديرية
                name_ar = row.get('اسم المرفق', '').strip()
                raw_type = row.get('النوع', '').strip()
                specialty = row.get('نوع المنشأة', '').strip()
                sector = row.get('القطاع', '').strip()
                # 'الحالة التشغيلية' -> default ACTIVE if '-'
                raw_status = row.get('الحالة التشغيلية', '').strip()
                governorate = row.get('المحافظة', '').strip()
                district = row.get('المديرية', '').strip()
                
                # Logic
                facility_type = FACILITY_TYPE_MAP.get(raw_type, 'OTHER')
                
                operational_status = 'ACTIVE'
                if raw_status != '-' and raw_status != '':
                     # If there's a status, we might need to map it. 
                     # For now, let's assume anything other than '-' is a specific status.
                     # But looking at CSV, most are '-'.
                     operational_status = 'ACTIVE' 
                
                # Generate a pseudo-unique code
                # e.g., FAC-{district_first_3}-{count}
                # Sanitize district for code
                dist_code = ''.join(c for c in district if c.isalnum())[:3].upper()
                if not dist_code: dist_code = "GEN"
                facility_code = f"FAC-{count:04d}" 

                # Prepare SQL values
                val_code = escape_sql(facility_code)
                val_name = escape_sql(name_ar)
                val_type = escape_sql(facility_type) # English code
                val_specialty = escape_sql(specialty)
                val_sector = escape_sql(sector)
                val_status = escape_sql(operational_status)
                val_gov = escape_sql(governorate)
                val_dist = escape_sql(district)
                
                # Insert statement
                # Columns: facility_code, name_ar, facility_type, specialty, sector, operational_status, governorate, district, license_type, is_active
                stmt = (
                    f"INSERT INTO facilities (facility_code, name_ar, facility_type, specialty, sector, operational_status, governorate, district, license_type, is_active) "
                    f"VALUES ({val_code}, {val_name}, {val_type}, {val_specialty}, {val_sector}, {val_status}, {val_gov}, {val_dist}, 'NEW', TRUE) "
                    f"ON CONFLICT (facility_code) DO NOTHING;"
                )
                sql_statements.append(stmt)

        print(f"Processed {count} rows.")
        
        # Write to file
        os.makedirs(os.path.dirname(OUTPUT_SQL_PATH), exist_ok=True)
        with open(OUTPUT_SQL_PATH, 'w', encoding='utf-8') as f:
            f.write('\n'.join(sql_statements))
            
        print(f"Successfully generated SQL at: {OUTPUT_SQL_PATH}")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    generate_sql()
